- name: Build
  hosts: all
  tasks:
  - name: cd
    shell: cd /home/bpmadmin/output
    become: yes
    become_user: bpmadmin
  - name: run jar
    shell: /opt/ibm/BPM/v8.5/java_1.7_64/bin/java -jar /home/bpmadmin/serviceBuilder.jar
    become: yes
    become_user: bpmadmin
