- name: Transfer and execute a script.
  hosts: all
  tasks:
  - name: touch
    shell: /home/bpmadmin/output
  - name: copy11
    shell: /opt/ibm/BPM/v8.5/java_1.7_64/bin/java -jar /home/bpmadmin/serviceBuilder.jar
