- name: Check out SVN Repository
  hosts: all
  vars_files:
  - "var_{{ TOWER_ENV }}.yml"
  tasks:
  - name: Check out SVN Repository
    subversion: repo={{ SVN_REPO }} 
                dest={{ SVN_DST }} 
                username={{ SVN_USER_NAME }} 
                password={{ SVN_USER_PASSWORD }}
    become: yes
    become_user: bpmadmin
