- name: Check out SVN Repository
  hosts: all
  vars_files:
  - /vars/external_vars.yml
  tasks:
  - name: Check out SVN Repository
    subversion: repo={{ SVN_REPO }} 
                dest={{ SVN_DST }} 
                username=gzheng
                password=YouGet1234
