- name: Check out SVN Repository
  hosts: all
  include_vars:
  - "var_{{ TOWER_ENV }}.yml"
  tasks:
  - name: Check out SVN Repository
    subversion: repo={{ SVN_REPO }} 
                dest={{ SVN_DST }} 
                username={{ SVN_USER_NAME }} 
                password={{ SVN_USER_PASSWORD }} 
