- name: Transfer and execute a script.
  hosts: all
  tasks:
  - name: Update code on app servers
      subversion: repo=svn+ssh://svn-01-dev-1.you-get.com/svn/repository/Integrations/DSPPortal/trunk/DSPConnectorPortalModule/
                  dest= /src/checkout
                  username= gzheng@you-get.com
                  password= YouGet1234
