- name: Check out SVN Repository
  hosts: all
  vars_files:
  - /tmp/dev.yml
  tasks:
  - name: Check out SVN Repository
    subversion: repo={{ SVN_REPO }} 
                dest={{ SVN_DST }} 
                username={{ SVN_USER_NAME }} 
                password=YouGet1234
