- name: Transfer and execute a script.
  hosts: all
  tasks:
    subversion:
      repo: svn+ssh://svn-01-dev-1.you-get.com/svn/repository/Integrations/DSPPortal/trunk/DSPConnectorPortalModule/
      dest: /src/export
