- name: Check out SVN Repository
  hosts: all
  tasks:
  - name: Check out SVN Repository
    subversion: repo={{ SVN_REPO }} 
                dest={{ SVN_DST }} 
                username=gzheng
                password=YouGet1234
