- name: Check out SVN Repository
  hosts: all
  include_vars:
    file: /tmp/{{ TOWER_ENC }}_dev.yml
    name: stuff
  tasks:
  - name: Check out SVN Repository
    subversion: repo={{ SVN_REPO }} 
                dest={{ SVN_DST }} 
                username={{ SVN_USER_NAME }} 
                password=YouGet1234
