- name: Transfer and execute a script.
  hosts: all
  tasks:
  - name: Update code on app servers
    subversion: repo={{ SVN_REPO }} 
                dest={{ SVN_DST }} 
                username=gzheng
                password=YouGet1234
